version: '3'

networks:
  programming_network:
    driver: bridge

services:
  nginx_pocket_be:
    image: nginx:1.22-alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./docker-config/nginx/conf:/etc/nginx/conf.d
      - ./docker-config/nginx/logs:/var/log/nginx
    networks:
      - programming_network

  mysql5729:
    image: mysql:5.7.29
    container_name: mysql57
    volumes:
      - ./docker-config/mysql5729:/var/lib/mysql
    restart: unless-stopped
    tty: true
    ports:
      - "3307:3306"
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: 983537
      MYSQL_ROOT_PASSWORD: 983537
    networks:
      - programming_network

  postgres144:
    image: postgres:14.4-alpine
    container_name: postgres14
    volumes:
      - ./docker-config/postgres144:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=983537
    networks:
      - programming_network

  php72:
    build:
      context: .
      dockerfile: ./docker-config/php72/Dockerfile
    container_name: php72
    restart: unless-stopped
    tty: true
    volumes:
      - ./src:/var/www/html
    ports:
      - "9072:9000"
    networks:
      - programming_network

  php81:
    build:
      context: .
      dockerfile: ./docker-config/php81/Dockerfile
    container_name: php81
    restart: unless-stopped
    tty: true
    environment:
      - XDEBUG_MODE=coverage
    volumes:
      - ./src:/var/www/html
    ports:
      - "9081:9000"
    networks:
      - programming_network